# Generated by Django 2.2 on 2020-01-15 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200115_0428'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
